# Generated by Django 5.1.4 on 2025-06-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.CharField(help_text="Unique ID for the candle record, e.g., 'NSE:SBIN-EQ_D_1690934400'.", max_length=255, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, help_text="The full Fyers symbol format, e.g., 'NSE:SBIN-EQ'.", max_length=100)),
                ('timeframe', models.CharField(help_text="The timeframe of the candle (e.g., '1', '5', '15', '60', 'D').", max_length=10)),
                ('datetime', models.DateTimeField(db_index=True, help_text='The timezone-aware timestamp for the start of the candle.')),
                ('open', models.FloatField(help_text='The opening price of the candle.')),
                ('high', models.FloatField(help_text='The highest price of the candle.')),
                ('low', models.FloatField(help_text='The lowest price of the candle.')),
                ('close', models.FloatField(help_text='The closing price of the candle.')),
                ('volume', models.BigIntegerField(help_text="The volume traded during the candle's duration.")),
            ],
            options={
                'verbose_name': 'Historical Candle',
                'verbose_name_plural': 'Historical Data',
                'db_table': 'historical_ohlcv',
                'unique_together': {('symbol', 'timeframe', 'datetime')},
            },
        ),
    ]
