# Generated by Django 5.1.4 on 2025-05-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenerCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_indicator', models.CharField(choices=[('close', 'Close'), ('sma', 'SMA'), ('ema', 'EMA'), ('rsi', 'RSI'), ('macd', 'MACD'), ('atr', 'ATR'), ('volume', 'Volume')], max_length=20)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '==')], max_length=3)),
                ('right_indicator', models.CharField(blank=True, choices=[('close', 'Close'), ('sma', 'SMA'), ('ema', 'EMA'), ('rsi', 'RSI'), ('macd', 'MACD'), ('atr', 'ATR'), ('volume', 'Volume')], max_length=20, null=True)),
                ('constant', models.FloatField(blank=True, null=True)),
                ('logic_with_next', models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], max_length=3, null=True)),
                ('screener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='screener.screener')),
            ],
        ),
    ]
