# Generated by Django 5.1.4 on 2025-05-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timeframe', models.CharField(choices=[('15min', '15-Minute'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('segment', models.CharField(choices=[('Nifty 50', 'Nifty 50'), ('Nifty 100', 'Nifty 100'), ('Nifty 500', 'Nifty 500'), ('All NSE', 'All NSE'), ('Custom', 'Custom')], default='Nifty 50', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='screenercondition',
            name='screener',
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_indicator', models.CharField(max_length=50)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '==')], max_length=2)),
                ('right_indicator', models.CharField(blank=True, max_length=50, null=True)),
                ('constant', models.FloatField(blank=True, null=True)),
                ('logic', models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], max_length=3, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='screener.scan')),
            ],
        ),
        migrations.DeleteModel(
            name='Screener',
        ),
        migrations.DeleteModel(
            name='ScreenerCondition',
        ),
    ]
