# Generated by Django 5.1.4 on 2025-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_scan_remove_screenercondition_screener_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters_json', models.JSONField()),
                ('segment', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
