# Generated by Django 5.1.4 on 2025-06-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarterlyfinancials',
            options={'ordering': ['company_name', '-period_end_date'], 'verbose_name_plural': 'Quarterly Financials'},
        ),
    ]
