# Generated by Django 5.1.4 on 2025-06-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fundamentals.industryclassification')),
            ],
            options={
                'verbose_name_plural': 'Industry Classifications',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bse_code', models.CharField(blank=True, max_length=50, null=True)),
                ('nse_code', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('high_low', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_pe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roce', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pros', models.JSONField(blank=True, default=list, null=True)),
                ('cons', models.JSONField(blank=True, default=list, null=True)),
                ('peer_comparison', models.JSONField(blank=True, default=list, null=True)),
                ('quarterly_results', models.JSONField(blank=True, default=list, null=True)),
                ('profit_loss_statement', models.JSONField(blank=True, default=list, null=True)),
                ('balance_sheet', models.JSONField(blank=True, default=list, null=True)),
                ('cash_flow_statement', models.JSONField(blank=True, default=list, null=True)),
                ('ratios', models.JSONField(blank=True, default=list, null=True)),
                ('compounded_sales_growth', models.JSONField(blank=True, default=dict, null=True)),
                ('compounded_profit_growth', models.JSONField(blank=True, default=dict, null=True)),
                ('stock_price_cagr', models.JSONField(blank=True, default=dict, null=True)),
                ('return_on_equity', models.JSONField(blank=True, default=dict, null=True)),
                ('shareholding_pattern', models.JSONField(blank=True, default=dict, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundamentals.industryclassification')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
